### PR TITLE
fix: update subgraph domain

### PR DESCRIPTION
**Pull request by viet-nv**

### CODE REVIEW

**Review by manhlx3006 — APPROVED** [review]

**Comment by piavgh** [comment]
pls update file `src/apollo/client.ts` also
The default value in reducer is still retrieved from that file

**Comment by viet-nv** [comment]
> pls update file `src/apollo/client.ts` also The default value in reducer is still retrieved from that file

Thanks, I updated to public subgraph

**Comment by piavgh** [comment]
> > pls update file `src/apollo/client.ts` also The default value in reducer is still retrieved from that file
> 
> Thanks, I updated to public subgraph

Screenshot at Dec 08 10-21-48 AM

There is 1 remaining place that has knstats, please help to update it :D

**Comment by viet-nv** [comment]
> > > pls update file `src/apollo/client.ts` also The default value in reducer is still retrieved from that file
> > 
> > 
> > Thanks, I updated to public subgraph
>
> 
> There is 1 remaining place that has knstats, please help to update it :D

My bad. updated :D

**Pull request merged**
